config/routes.rb
Rails.application.routes.draw do

	root 'products#index'

 	resources :products

 	resources :users, only: [:new, :create, :edit, :update]

 	resources :sessions, only: [:new, :create, :destroy]

 	resources :products do
 		resources :reviews, only: [:show, :create, :destroy]
 	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
	
	validates :description, :name, :url, presence: true
	validates :price, numericality: {only_integer: true}
	
	has_many :reviews, dependent: :destroy
	has_many :users, through: :reviews
	belongs_to :category
	
	def formatted_price
		"$%.2f" % (price.to_f / 100)
	end

end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :product
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :name, presence: true
	validates :email, uniqueness: true
	
	has_many :reviews
	has_many :products, through: :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "Please log in"
  		redirect_to new_session_path
  	end
  end

  private
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :ensure_logged_in, only: [:new, :edit, :destroy]

	def index
		@products = Product.all
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to product_path(@product)
		else
			render :new
		end
	end

	def show
		@product = Product.find(params[:id])

		if current_user
			@review = @product.reviews.build
		end
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		if @product.update_attributes(product_params)
			redirect_to product_path(@product)
		else
			render :edit
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path
	end

  private
  def product_params
  	params.require(:product).permit(:name, :description, :price, :url, :category_id)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :ensure_logged_in, only: [:create, :destroy]
  
  def show
  	@review = Review.find(params[:id])
  end

  def create
  	@product = Product.find(params[:product_id])
    @review = @product.reviews.build(review_params)
    @review.user = current_user
    if @review.save
      redirect_to product_path(@product), notice: "Review created successfully!"
    else
      render 'products/show'
    end
  end

  def destroy
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@product)
  end

  private
  def review_params
    params.require(:review).permit(:comment, :product_id )
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render 'new'
    end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to products_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new 
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to products_url, notice: "Signed up!"
		else
			render :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to products_url
		else
			render :edit
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
end
	end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Rainforest</title>
	  <%= stylesheet_link_tag    'application', media: 'all' %>
	  <%= javascript_include_tag 'application' %>
	  <%= csrf_meta_tags %>
	  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine&effect=fire-animation|ice|putting-green|fire|splintered">
	</head>

	<body class="<%= controller_name %> <%= action_name %>">


	  <nav class="navbar navbar-inverse">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      </em><h1 class="navbar-brand">Rainforest</h1>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		        <li class="active"><%= link_to "Home", "/" %></li>
		        <li><%= link_to "Add New Product", "/products/new" %></li>
		        
		      </ul>
		      
		      <ul class="nav navbar-nav navbar-right">
      			<% if current_user %>
			        <li class="dropdown">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
			          <ul class="dropdown-menu" role="menu">
      						<li><%= link_to "Log out", session_path("current"), :method => :delete %></li>
      						<li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
			          </ul>
			        </li>
      			<% else %>
		        	<li><%= link_to "Log in", new_session_path %></li>
		          <li><%= link_to "Sign up", new_user_path %></li>
						<% end %>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav> 

   
		<div class="container" >
		  <% if flash[:notice] %>
	      <p id="notice"><%= flash[:notice] %></p>
	    <% end %>
	    <% if flash[:alert] %>
	      <p id="alert"><%= flash[:alert] %></p>
	    <% end %>
			<%= yield %>
		</div>

	</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %> 

app/views/products/edit.html.erb
<div class="font-effect-putting-green">
  <h1>Edit Product</h1>

<%= form_for(@product, html: {class: "form-horizontal"}) do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
    <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
    <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :price, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :url, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :url, class: "form-control" %>
    </div>
  </div>
  <%= f.label :category %>
</div>  
  <%= f.select(:category_id) do %>
    <%= Category.all.each do |c| %>
    <%= content_tag(:option, c.name, value: c.id) %>
    <% end %>
  <% end %>
  <div class="form-group">
    <div class="col-sm-10">
    <%= f.submit "Update", class: "btn-success" %>
    </div>
  </div>
<% end %>
<%= link_to "Back", "/products/#{@product.id}" %>

app/views/products/index.html.erb
<div class="font-effect-fire-animation">
	<h1>Top 10 Products</h1>		

<ol class="index">
	<% @products.each do |product| %>
	  <li><%= link_to "#{product.name}-#{product.formatted_price}", product_path(product) %><span class="label label-default"><%= product.category.name %></span>
  			<%= image_tag product.url %>
	  </li>
	<% end %>
</ol>	
</div>

app/views/products/new.html.erb
<div class="font-effect-ice">
  <h1>Add New Product</h1>


<% if @product.errors.any? %>
  <% @product.errors.full_messages.each do |msg| %>
  <li> <%= msg %> </li>
  <% end %>
<% end %>

<%= form_for(@product, html: {class: "form-horizontal"}) do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
    <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
    <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :price, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :url, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :url, class: "form-control" %>
    </div>
  </div>
  <%= f.label :category %>
</div>    
  <%= f.select(:category_id) do %>
    <%= Category.all.each do |c| %>
    <%= content_tag(:option, c.name, value: c.id) %>
    <% end %>
  <% end %>

  <div class="form-group">
    <div class="col-sm-10">
    <%= f.submit "Save", class: "btn-info" %>
    </div>
  </div>
<% end %>
<section class="footer">
  <%= link_to "Back", products_path %>  
</section>

app/views/products/show.html.erb
<section class="show">
<div class="font-effect-fire">
  <h1><%= @product.name %></h1>  
</div>

<p><%= @product.description %></p>
<p><%= @product.formatted_price %></p>
<%= image_tag @product.url %>
</section>

<div class="font-effect-splintered">
<section class="review">
<h2>Reviews for <%= @product.name %></h2>
<% @product.reviews.order("updated_at desc").each do |review| %>
  <p>
    <%= review.comment %>
    <% if review.user == current_user %> 
      <%= link_to "Delete", product_review_path(@product, review), method: :delete %>
    <% end %>  
    <br>
    <% if review.user != nil %>
      <em> by <%= review.user.name %></em>
      Added on: <%= review.created_at %>
    <% end %>
  </p>
<% end %>
</section>
</div>

<% if current_user %>
  <h3>Add your comment below!</h3>
	<%= form_for([@product, @review]) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
  <%= link_to "Edit", edit_product_path(@product) %> |
  <%= link_to "Delete", @product, method: :delete, data: {confirm: "Are you sure you want to delete this product?"} %> |

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p> 
<% end %>

<%= link_to "Back", "/products" %> 

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= form_for @user, html: {class: "form-horizontal"} do |f| %>
	<div class="form-group">
    <%= f.label :name, {class: "col-sm-2 control-label"} %>
    <div class="col-sm-10">
    <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, {class: "col-sm-2 control-label"} %>
    <div class="col-sm-10">
    <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, {class: "col-sm-2 control-label"} %>
    <div class="col-sm-10">
    <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, {class: "col-sm-2 control-label"} %>
    <div class="col-sm-10">
    <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>  

app/views/users/new.html.erb
<h1>Sing Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>  
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>  